### ISSUE TITLE
Bike

### ISSUE THREAD

**Issue by mootactics** [noxsicarius/R3F-Tow-Lift#1]
I have deploy bike setup on my server, 
the take option makes it kick you for pub restrict #0
Load In is another useless function honestly.. Should make stuff like that optional. 
I would highly recommend just removing all of the stuff like that or at least provide a way to do so.

**Comment by noxsicarius** [comment]
What is the take option? and the R3F mod is not mine. I simply host a stable modified version of it for my youtube channel. Unless I wrote the mod I haven't done severe modifications to the code. I plan on making this more stable in the future so I may consider a variable for removing the load in. I have used it for bikes when going to the air fields. Really useful for storing a quite fast vehicle.

**Comment by mootactics** [comment]
Here is the updated error/bug view so you can see what goes on.
The bike works perfectly how it should up until you get on it, then after you 'get out' it gives these options..
![error bugs1 tow](https://cloud.githubusercontent.com/assets/8845589/4351743/d1db23d0-4213-11e4-95ec-ff2efb55c7c5.png)
It gives you the capability to move the bike completely around you, basically like a placement item.
It functions for about 1-3 seconds then kicks me, this is the message. 
![error bugs2 tow](https://cloud.githubusercontent.com/assets/8845589/4351747/da5ec714-4213-11e4-97da-7aec95ccc1d7.png)

I would prefer to remove it entirely but I don't know how to and it wasn't there until I added in the towing script.

**Comment by noxsicarius** [comment]
I need to look more into this. I don't have a take option, only a load in for the bike.

**Comment by mootactics** [comment]
I still have this issue after reinstalling it several times..  
Just so you're aware, I am running Epoch 1.0.5.1 & Overwatch 0.2.5 (Overpoch)
