### ISSUE TITLE
Lock/Unlock

### ISSUE THREAD

**Issue by mootactics** [noxsicarius/R3F-Tow-Lift#2]
Keeps giving the option to unlock, multiples as you do so even when not near vehicle. 
So in the end you will have like
3 unlock selections, even if the vehicle is unlocked. 
![errorbugs3](https://cloud.githubusercontent.com/assets/8845589/4352071/b439ddea-421c-11e4-9e3a-f92204f3ec5d.png)
The unlocks also stay up after you leave the vehicle, even if you're not facing it. 

![errorbugs4](https://cloud.githubusercontent.com/assets/8845589/4352074/ba9912dc-421c-11e4-91a6-9c00c38038b0.png)

**Comment by mootactics** [comment]
Updated to include images.

**Comment by noxsicarius** [comment]
Try removing and reinstalling the script. I tried a fresh install yesterday and it worked fine without this issue.

**Comment by mootactics** [comment]
Tried that, didnt work.  Still listing multiples and multiples ..
