### ISSUE TITLE
Does this script still works for 1.0.6

### ISSUE THREAD

**Issue by Stijnkluiters** [noxsicarius/R3F-Tow-Lift#3]
Hello dude,

I want to use this script in my server. would you think it will work on the newest patch?

If not, could you tell me which parts i should look in the code if something is outdated?
I can patch this version a bit up if you want me to :P

- Chargedlight1

**Comment by noxsicarius** [comment]
I believe it should work. I think they used their own handlers for everything. I haven't personally tested it, but I haven't heard about any problems about this.
